DELETE http://localhost:3001/api/persons/2
###
GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/2
###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "1234"
}
###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "",
    "number": "1234"
}
###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "new",
    "number": "1234"
}
